# fly.toml
app = "fastfolderbackend"
primary_region = "jnb"

[build]

[env]
  PORT = "5000"                 # server.js reads this; must match internal_port
  UPLOAD_DIR = "/data/uploads"  # persisted on the volume
  PUBLIC_BASE_URL = "https://fastfolderbackend.fly.dev"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  app = "npm start"

# Persist /data so /data/uploads survives restarts/redeploys
[[mounts]]
  source = "uploads"
  destination = "/data"
